# Generated by Django 5.1.3 on 2024-11-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDatacenter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'dashboard_datacenter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardDomain',
            fields=[
                ('uuid', models.UUIDField(db_column='UUID', primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('max_ram', models.IntegerField()),
                ('current_ram', models.IntegerField()),
                ('vcpus', models.IntegerField()),
                ('vnc_port', models.IntegerField(blank=True, null=True)),
                ('proxy_port', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(max_length=15)),
                ('mac_address', models.CharField(blank=True, db_column='mac-address', max_length=18, null=True)),
            ],
            options={
                'db_table': 'dashboard_domain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dashboard_node',
                'managed': False,
            },
        ),
    ]
